[whois]
enabled = true
backend = "bgpview"

[[ip_lists]]
asns = [15169, 395973, 396982]
name = "Google"

[[ip_lists]]
name = "GoogleChat"
domains = [
"alt5-mtalk.google.com",
"mtalk.google.com",
"alt4-mtalk.google.com",
"alt3-mtalk.google.com",
"alt2-mtalk.google.com",
"hangouts.google.com",
"plus.l.google.com",
]

[[ip_lists]]
name = "Discord"
# incomplete list of domains that have been seen so far.
domains = [
"us-east38.discord.media",
"discord.media",
"discord.gg",
"discordapp.com",
"discordapp.gg",
"gateway.discord.gg",
"latency.discord.media",
"status.discord.com",
"media.discordapp.net",
"cdn.discordapp.com",
"us-east5053.discord.media",
"images-ext-2.discordapp.net",
"images-ext-1.discordapp.net",
"us-east1993.discord.media",
]


[[ip_lists]]
name = "MailServers"
domains = [
# incomplete list of mail servers that have been seen so far.
"imap.gmail.com",
"smtp.gmail.com",
"mail.google.com",
"imap-mail.outlook.com",
"pop-mail.outlook.com",
"imap.mail.me.com",
"smtp.mail.me.com",
]

[[ip_lists]]
name = "Minecraft"
domains = ["minecraft.com","pc.realms.minecraft.net","mojang.com"]

[[ip_lists]]
asns = [714]
domains = ["apple.com"]
name = "Apple"

[[ip_lists]]
asns = [41231]
domains = ["ubuntu.com"]
name = "Canonical"

[[ip_lists]]
asns = [394073]
name = "Bungie"

[[ip_lists]]
asns = [14061]
domains = ["cloud.digitalocean.com"]
name = "DigitalOcean"

[[ip_lists]]
asns = [54372]
name = "DropBox"

[[ip_lists]]
asns = [33517]
name = "DynLTD"

[[ip_lists]]
asns = [7060]
name = "EA"

[[ip_lists]]
asns = [11278]
name = "Nintendo"

[[ip_lists]]
asns = [202081]
name = "GOG"

[[ip_lists]]
asns = [4356]
name = "EpicGames"

[[ip_lists]]
asns = [32934, 63293]
name = "Facebook"

[[ip_lists]]
asns = [23286]
name = "Hulu"

[[ip_lists]]
asns = [49544]
name = "I3D"

[[ip_lists]]
asns = [22622]
name = "LimeLight"

[[ip_lists]]
asns = [2906, 40027]
name = "Netflix"

[[ip_lists]]
asns = [90]
name = "Oracle"

[[ip_lists]]
asns = [22697]
name = "Roblox"

[[ip_lists]]
asns = [395291]
name = "SnapChat"

[[ip_lists]]
asns = [8403]
name = "Spotify"

[[ip_lists]]
asns = [138699]
name = "TikTok"

[[ip_lists]]
asns = [13414, 35995]
name = "Twitter"

[[ip_lists]]
asns = [55743, 49078, 22634]
name = "Ubisoft"

[[ip_lists]]
asns = [32590]
name = "Valve"

[[ip_lists]]
asns = [11917]
name = "WhatsApp"
