# Maximum width of an array literal before falling back to vertical formatting.
array_width = 100
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
chain_width = 100
color = "Auto"
combine_control_expr = true
comment_width = 100
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
edition = "2018"
emit_mode = "Files"
empty_item_single_line = false
enum_discrim_align_threshold = 30
error_on_line_overflow = false
error_on_unformatted = false
fn_args_layout = "Tall"
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
hard_tabs = false
hide_parse_errors = true
ignore = ["target/**", "dist/**", "public/**", "vendor/**", ".cargo/**"]
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 50
make_backup = false
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 100
merge_derives = true
merge_imports = true
newline_style = "Unix"
normalize_comments = false
normalize_doc_attributes = false
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
# required_version = "1.2.2"
single_line_if_else_max_width = 98
skip_children = false
space_after_colon = true
space_around_attr_eq = false
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 60
struct_lit_single_line = true
tab_spaces = 2
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Compressed"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
# version = "One"
where_single_line = true
wrap_comments = true
