name: Rust

on:
  schedule:
  - cron: "0 2 * * *"
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run with default config.
      run: cargo run
#     - name: Build Release
#       run: cargo build --verbose --release

      
